mac_packages = {
    "App Store:AppIcon": "app_store",
    "Reminders:Reminders": "bell",
    "Reminders:icon": "bell",
    "Calendar:App": "calendar",
    "Calendar:App-empty": "calendar",
    "Image Capture:ImageCapture": "capture",
    "Dashboard:Dashboard": "dashboard",
    "Font Book:appicon": "font",
    "Photos:AppIcon": "gallery",
    "Home:AppIcon-mac": "home",
    "Maps:maps": "location",
    "Messages:MessagesAppIcon": "message",
    "Siri:Siri": "microphone",
    "Mounty:AppIcon": "mountains",
    "iTunes:iTunes": "music",
    "Preview:Preview": "preview",
    "QuickTime Player:QuickTimePlayerX": "quicktime",
    "Automator:Automator": "robot_arm",
    "Automator:AutomatorApplet": "robot_arm",
    "Safari:compass": "safari",
    "Visual Studio Code:Code": "vscode",
    "Utilities/ColorSync Utility:ColorSyncUtility": "sync",
    "Utilities/Terminal:Terminal": "terminal",
    "Utilities/AU Lab:PPIcon": "wave",
}
